INSERT  INTO
	alipay_autoresponse_default
      ( 
      id                            
      ,templatename                   
      ,templateid                     
      ,msgtype                        
      ,accountid                      
      ,iswork                         
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :alipayAutoresponseDefault.id                            
      ,:alipayAutoresponseDefault.templatename                  
      ,:alipayAutoresponseDefault.templateid                    
      ,:alipayAutoresponseDefault.msgtype                       
      ,:alipayAutoresponseDefault.accountid                     
      ,:alipayAutoresponseDefault.iswork                        
      ,:alipayAutoresponseDefault.createName                    
      ,:alipayAutoresponseDefault.createBy                      
      ,:alipayAutoresponseDefault.createDate                    
      ,:alipayAutoresponseDefault.updateName                    
      ,:alipayAutoresponseDefault.updateBy                      
      ,:alipayAutoresponseDefault.updateDate                    
      )