INSERT  INTO
	alipay_gzuserinfo
      ( 
      id                            
      ,userid                         
      ,name                           
      ,department                     
      ,position                       
      ,mobile                         
      ,province                       
      ,gender                         
      ,email                          
      ,weixinid                       
      ,avatar                         
      ,subscribe_status               
      ,subscribe_time                 
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :alipayGzuserinfo.id                            
      ,:alipayGzuserinfo.userid                        
      ,:alipayGzuserinfo.name                          
      ,:alipayGzuserinfo.department                    
      ,:alipayGzuserinfo.position                      
      ,:alipayGzuserinfo.mobile                        
      ,:alipayGzuserinfo.province                      
      ,:alipayGzuserinfo.gender                        
      ,:alipayGzuserinfo.email                         
      ,:alipayGzuserinfo.weixinid                      
      ,:alipayGzuserinfo.avatar                        
      ,:alipayGzuserinfo.subscribeStatus               
      ,:alipayGzuserinfo.subscribeTime                 
      ,:alipayGzuserinfo.accountid                     
      ,:alipayGzuserinfo.createName                    
      ,:alipayGzuserinfo.createBy                      
      ,:alipayGzuserinfo.createDate                    
      ,:alipayGzuserinfo.updateName                    
      ,:alipayGzuserinfo.updateBy                      
      ,:alipayGzuserinfo.updateDate                    
      )