INSERT  INTO
	alipay_autoresponse
      ( 
      id                            
      ,key_word                       
      ,res_content                    
      ,msg_type                       
      ,template_name                  
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :alipayAutoresponse.id                            
      ,:alipayAutoresponse.keyWord                       
      ,:alipayAutoresponse.resContent                    
      ,:alipayAutoresponse.msgType                       
      ,:alipayAutoresponse.templateName                  
      ,:alipayAutoresponse.accountid                     
      ,:alipayAutoresponse.createName                    
      ,:alipayAutoresponse.createBy                      
      ,:alipayAutoresponse.createDate                    
      ,:alipayAutoresponse.updateName                    
      ,:alipayAutoresponse.updateBy                      
      ,:alipayAutoresponse.updateDate                    
      )