INSERT  INTO
	alipay_gzentity
      ( 
      id                            
      ,template_name                  
      ,template_id                    
      ,template_type                  
      ,is_work                        
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :alipayGzentity.id                            
      ,:alipayGzentity.templateName                  
      ,:alipayGzentity.templateId                    
      ,:alipayGzentity.templateType                  
      ,:alipayGzentity.isWork                        
      ,:alipayGzentity.accountid                     
      ,:alipayGzentity.createName                    
      ,:alipayGzentity.createBy                      
      ,:alipayGzentity.createDate                    
      ,:alipayGzentity.updateName                    
      ,:alipayGzentity.updateBy                      
      ,:alipayGzentity.updateDate                    
      )