INSERT  INTO
	qywx_autoresponse_default
      ( 
      id                            
      ,templatename                   
      ,templateid                     
      ,msgtype                        
      ,accountid                      
      ,iswork                         
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxAutoresponseDefault.id                            
      ,:qywxAutoresponseDefault.templatename                  
      ,:qywxAutoresponseDefault.templateid                    
      ,:qywxAutoresponseDefault.msgtype                       
      ,:qywxAutoresponseDefault.accountid                     
      ,:qywxAutoresponseDefault.iswork                        
      ,:qywxAutoresponseDefault.createName                    
      ,:qywxAutoresponseDefault.createBy                      
      ,:qywxAutoresponseDefault.createDate                    
      ,:qywxAutoresponseDefault.updateName                    
      ,:qywxAutoresponseDefault.updateBy                      
      ,:qywxAutoresponseDefault.updateDate                    
      )