INSERT  INTO
	qywx_gzentity
      ( 
      id                            
      ,template_name                  
      ,template_id                    
      ,template_type                  
      ,is_work                        
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxGzentity.id                            
      ,:qywxGzentity.templateName                  
      ,:qywxGzentity.templateId                    
      ,:qywxGzentity.templateType                  
      ,:qywxGzentity.isWork                        
      ,:qywxGzentity.accountid                     
      ,:qywxGzentity.createName                    
      ,:qywxGzentity.createBy                      
      ,:qywxGzentity.createDate                    
      ,:qywxGzentity.updateName                    
      ,:qywxGzentity.updateBy                      
      ,:qywxGzentity.updateDate                    
      )