INSERT  INTO
	qywx_receivetext
      ( 
      id                            
      ,tousername                     
      ,fromusername                   
      ,createtime                     
      ,msgtype                        
      ,msgid                          
      ,content                        
      ,response                       
      ,rescontent                     
      ,nickname                       
      ,accountid
      ,agent_id
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxReceivetext.id                            
      ,:qywxReceivetext.tousername                    
      ,:qywxReceivetext.fromusername                  
      ,:qywxReceivetext.createtime                    
      ,:qywxReceivetext.msgtype                       
      ,:qywxReceivetext.msgid                         
      ,:qywxReceivetext.content                       
      ,:qywxReceivetext.response                      
      ,:qywxReceivetext.rescontent                    
      ,:qywxReceivetext.nickname                      
      ,:qywxReceivetext.accountid  
      ,:qywxReceivetext.agentId
      ,:qywxReceivetext.createName                    
      ,:qywxReceivetext.createBy                      
      ,:qywxReceivetext.createDate                    
      ,:qywxReceivetext.updateName                    
      ,:qywxReceivetext.updateBy                      
      ,:qywxReceivetext.updateDate                    
      )