INSERT  INTO
	qywx_group
      ( 
      id                            
      ,name                           
      ,parentid
      ,orders
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxGroup.id                            
      ,:qywxGroup.name                          
      ,:qywxGroup.parentid
      ,:qywxGroup.orders
      ,:qywxGroup.accountid                     
      ,:qywxGroup.createName                    
      ,:qywxGroup.createBy                      
      ,:qywxGroup.createDate                    
      ,:qywxGroup.updateName                    
      ,:qywxGroup.updateBy                      
      ,:qywxGroup.updateDate                    
      )