INSERT  INTO
	qywx_gzuserinfo
      ( 
      id                            
      ,userid                         
      ,name                           
      ,department                     
      ,position                       
      ,mobile                         
      ,province                       
      ,gender                         
      ,email                          
      ,weixinid                       
      ,avatar                         
      ,subscribe_status               
      ,subscribe_time                 
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxGzuserinfo.id                            
      ,:qywxGzuserinfo.userid                        
      ,:qywxGzuserinfo.name                          
      ,:qywxGzuserinfo.department                    
      ,:qywxGzuserinfo.position                      
      ,:qywxGzuserinfo.mobile                        
      ,:qywxGzuserinfo.province                      
      ,:qywxGzuserinfo.gender                        
      ,:qywxGzuserinfo.email                         
      ,:qywxGzuserinfo.weixinid                      
      ,:qywxGzuserinfo.avatar                        
      ,:qywxGzuserinfo.subscribeStatus               
      ,:qywxGzuserinfo.subscribeTime                 
      ,:qywxGzuserinfo.accountid                     
      ,:qywxGzuserinfo.createName                    
      ,:qywxGzuserinfo.createBy                      
      ,:qywxGzuserinfo.createDate                    
      ,:qywxGzuserinfo.updateName                    
      ,:qywxGzuserinfo.updateBy                      
      ,:qywxGzuserinfo.updateDate                    
      )