INSERT  INTO
	qywx_account
      ( 
      id                            
      ,accont_name                    
      ,account_desc                   
      ,access_token                   
      ,secret      
      ,conversation_secret
      ,corpid                         
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxAccount.id                            
      ,:qywxAccount.accontName                    
      ,:qywxAccount.accountDesc                   
      ,:qywxAccount.accessToken                   
      ,:qywxAccount.secret  
      ,:qywxAccount.conversationSecret  
      ,:qywxAccount.corpid                        
      ,:qywxAccount.createName                    
      ,:qywxAccount.createBy                      
      ,:qywxAccount.createDate                    
      ,:qywxAccount.updateName                    
      ,:qywxAccount.updateBy                      
      ,:qywxAccount.updateDate                    
      )