INSERT  INTO
	alipay_menu
      ( 
      ID                            
      ,menu_name                      
      ,menu_type                      
      ,menu_key                       
      ,orders                         
      ,msg_type                       
      ,template_id                     
      ,url                            
      ,father_id                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date  
      ) 
values
      (
      :alipayMenu.id                            
      ,:alipayMenu.menuName                      
      ,:alipayMenu.menuType                      
      ,:alipayMenu.menuKey                       
      ,:alipayMenu.orders                        
      ,:alipayMenu.msgType                       
      ,:alipayMenu.templateId                    
      ,:alipayMenu.url                           
      ,:alipayMenu.fatherId                     
      ,:alipayMenu.createName                    
      ,:alipayMenu.createBy                      
      ,:alipayMenu.createDate                    
      ,:alipayMenu.updateName                    
      ,:alipayMenu.updateBy                      
      ,:alipayMenu.updateDate 
      )