INSERT  INTO
	alipay_newsitem
      ( 
      id                            
      ,title                          
      ,author                         
      ,image_path                     
      ,content                        
      ,templateid                     
      ,description                    
      ,order_no                       
      ,url                            
      ,hdid                           
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :alipayNewsitem.id                            
      ,:alipayNewsitem.title                         
      ,:alipayNewsitem.author                        
      ,:alipayNewsitem.imagePath                     
      ,:alipayNewsitem.content                       
      ,:alipayNewsitem.templateid                    
      ,:alipayNewsitem.description                   
      ,:alipayNewsitem.orderNo                       
      ,:alipayNewsitem.url                           
      ,:alipayNewsitem.hdid                          
      ,:alipayNewsitem.createName                    
      ,:alipayNewsitem.createBy                      
      ,:alipayNewsitem.createDate                    
      ,:alipayNewsitem.updateName                    
      ,:alipayNewsitem.updateBy                      
      ,:alipayNewsitem.updateDate                    
      )