INSERT  INTO
	qywx_newsitem
      ( 
      id                            
      ,title                          
      ,author                         
      ,image_path                     
      ,content                        
      ,templateid                     
      ,description                    
      ,order_no                       
      ,url                            
      ,hdid                           
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxNewsitem.id                            
      ,:qywxNewsitem.title                         
      ,:qywxNewsitem.author                        
      ,:qywxNewsitem.imagePath                     
      ,:qywxNewsitem.content                       
      ,:qywxNewsitem.templateid                    
      ,:qywxNewsitem.description                   
      ,:qywxNewsitem.orderNo                       
      ,:qywxNewsitem.url                           
      ,:qywxNewsitem.hdid                          
      ,:qywxNewsitem.createName                    
      ,:qywxNewsitem.createBy                      
      ,:qywxNewsitem.createDate                    
      ,:qywxNewsitem.updateName                    
      ,:qywxNewsitem.updateBy                      
      ,:qywxNewsitem.updateDate                    
      )