INSERT  INTO
	qywx_newstemplate
      ( 
      id                            
      ,template_name                   
      ,template_type                   
      ,accountid                      
      ,create_name                    
      ,create_by                      
      ,create_date                    
      ,update_name                    
      ,update_by                      
      ,update_date                    
      ) 
values
      (
      :qywxNewstemplate.id                            
      ,:qywxNewstemplate.templateName                   
      ,:qywxNewstemplate.templateType                   
      ,:qywxNewstemplate.accountid                     
      ,:qywxNewstemplate.createName                    
      ,:qywxNewstemplate.createBy                      
      ,:qywxNewstemplate.createDate                    
      ,:qywxNewstemplate.updateName                    
      ,:qywxNewstemplate.updateBy                      
      ,:qywxNewstemplate.updateDate                    
      )